create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  bio text not null default '',
  location text not null default '',
  photo_url text,
  birth_date date,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists birth_date date;

alter table public.profiles enable row level security;

drop policy if exists "Inloggade kan läsa profiler" on public.profiles;
drop policy if exists "Användare kan skapa sin egen profil" on public.profiles;
drop policy if exists "Användare kan ändra sin egen profil" on public.profiles;

create policy "Inloggade kan läsa profiler"
on public.profiles for select to authenticated
using (true);

create policy "Användare kan skapa sin egen profil"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

create policy "Användare kan ändra sin egen profil"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create table if not exists public.follows (
  follower_id uuid not null references auth.users(id) on delete cascade,
  following_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

alter table public.follows enable row level security;

drop policy if exists "Inloggade kan läsa följningar" on public.follows;
drop policy if exists "Användare kan följa" on public.follows;
drop policy if exists "Användare kan sluta följa" on public.follows;

create policy "Inloggade kan läsa följningar"
on public.follows for select to authenticated
using (true);

create policy "Användare kan följa"
on public.follows for insert to authenticated
with check (auth.uid() = follower_id);

create policy "Användare kan sluta följa"
on public.follows for delete to authenticated
using (auth.uid() = follower_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  text text not null default '',
  recipe_id text,
  created_at timestamptz not null default now(),
  check (sender_id <> receiver_id),
  check (length(text) > 0 or recipe_id is not null)
);

alter table public.messages enable row level security;

drop policy if exists "Användare kan läsa sina meddelanden" on public.messages;
drop policy if exists "Användare kan skicka meddelanden" on public.messages;

create policy "Användare kan läsa sina meddelanden"
on public.messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

create policy "Användare kan skicka meddelanden"
on public.messages for insert to authenticated
with check (auth.uid() = sender_id);

create table if not exists public.recipes (
  id text primary key,
  author_id uuid not null references auth.users(id) on delete cascade,
  data jsonb not null,
  photo text,
  photos jsonb,
  created_at timestamptz not null default now()
);

alter table public.recipes add column if not exists photo text;
alter table public.recipes add column if not exists photos jsonb;
alter table public.recipes enable row level security;

drop policy if exists "Inloggade kan läsa recept" on public.recipes;
create policy "Inloggade kan läsa recept"
on public.recipes for select to authenticated
using (true);

drop policy if exists "Användare kan skapa recept" on public.recipes;
create policy "Användare kan skapa recept"
on public.recipes for insert to authenticated
with check (auth.uid() = author_id);

drop policy if exists "Användare kan uppdatera sina recept" on public.recipes;
create policy "Användare kan uppdatera sina recept"
on public.recipes for update to authenticated
using (auth.uid() = author_id)
with check (auth.uid() = author_id);

drop policy if exists "Användare kan ta bort sina recept" on public.recipes;
create policy "Användare kan ta bort sina recept"
on public.recipes for delete to authenticated
using (auth.uid() = author_id);

create table if not exists public.cooks (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  recipe_id text,
  data jsonb not null,
  photo text,
  photos jsonb,
  created_at timestamptz not null default now()
);

alter table public.cooks add column if not exists photo text;
alter table public.cooks add column if not exists photos jsonb;
alter table public.cooks enable row level security;

drop policy if exists "Inloggade kan läsa inlägg" on public.cooks;
create policy "Inloggade kan läsa inlägg"
on public.cooks for select to authenticated
using (true);

drop policy if exists "Användare kan skapa inlägg" on public.cooks;
create policy "Användare kan skapa inlägg"
on public.cooks for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Användare kan uppdatera sina inlägg" on public.cooks;
create policy "Användare kan uppdatera sina inlägg"
on public.cooks for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Användare kan ta bort sina inlägg" on public.cooks;
create policy "Användare kan ta bort sina inlägg"
on public.cooks for delete to authenticated
using (auth.uid() = user_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  cook_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null,
  created_at timestamptz not null default now()
);

alter table public.comments enable row level security;

drop policy if exists "Inloggade kan läsa kommentarer" on public.comments;
create policy "Inloggade kan läsa kommentarer"
on public.comments for select to authenticated
using (true);

drop policy if exists "Användare kan skriva kommentarer" on public.comments;
create policy "Användare kan skriva kommentarer"
on public.comments for insert to authenticated
with check (auth.uid() = user_id);

create table if not exists public.mums (
  cook_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (cook_id, user_id)
);

alter table public.mums enable row level security;

drop policy if exists "Inloggade kan läsa mums" on public.mums;
create policy "Inloggade kan läsa mums"
on public.mums for select to authenticated
using (true);

drop policy if exists "Användare kan ge mums" on public.mums;
create policy "Användare kan ge mums"
on public.mums for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Användare kan uppdatera sin mums" on public.mums;
create policy "Användare kan uppdatera sin mums"
on public.mums for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists public.saves (
  recipe_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (recipe_id, user_id)
);

alter table public.saves enable row level security;

drop policy if exists "Inloggade kan läsa sparade recept" on public.saves;
create policy "Inloggade kan läsa sparade recept"
on public.saves for select to authenticated
using (true);

drop policy if exists "Användare kan spara recept" on public.saves;
create policy "Användare kan spara recept"
on public.saves for insert to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Användare kan uppdatera sina sparade recept" on public.saves;
create policy "Användare kan uppdatera sina sparade recept"
on public.saves for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Användare kan avspara recept" on public.saves;
create policy "Användare kan avspara recept"
on public.saves for delete to authenticated
using (auth.uid() = user_id);
